### ISSUE TITLE
Increaseing gap limit

### ISSUE THREAD

**Issue by ghost** [PulpCattel/Spawn#2]
Not sure if this is relevant, but the spawn wallet could have an increased gap limit [say 100] and then the user can deposit to more addresses.
The gap limit is noted in the wallet.json file, so it would be included in the digital backup, but it would have to be specified again for the recovery word import...

https://github.com/PulpCattel/Spawn/blob/master/README.md#L76

**Comment by PulpCattel** [comment]
The limit of 20 is just an arbitrary number by me. Basically to remind me that spawned.json should not be used extensively, so a limit reminds me to renew it.

Note that the Wasabi's RPC generates address starting from `84'/0'/0/'/0/21`, so you could already generate more addresses without increasing the gap limit.
Important to specify that at wallet recovery the gap limit should be increased to find all the addresses, I should add that to the README.

**Comment by ghost** [comment]
alright - I think I misunderstood the reason for number 10/20 then.
Good job - thank you - this script is great!

**Comment by PulpCattel** [comment]
I've add it to the README, now should be a bit more clear.
